baseURL = "https://fire-transcriptomics-of-disease.github.io/fire-cb-2021-training/"
languageCode = "en-us"
title = "2021 FIRE-CB Training Modules"
theme = "ananke"

[markup.goldmark.renderer]
unsafe= true